#!/usr/bin/env bash
# script to display information about domains/subdomains

displayDomainInfo () {

    line=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $line" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" == 1 ]
then
    displayDomainInfo "$1" "www"
    displayDomainInfo "$2" "lb-01"  
    displayDomainInfo "$1" "web-01"
    displayDomainInfo "$1" "web-02"
elif [ "$#" == 2 ]
then
    displayDomainInfo "$1" "$2"
fi
