#!/usr/bin/env bash
#bash script to install nginx on server

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx start
sudo chown -R "$USER":"$USER" /var/www/html/index.html
sudo echo 'Hello World' > /var/www/html/index.html