#!/usr/bin/env bash
# script to install loadbalancer with provided configurations


configurations="
frontend haProxy
    bind *:80
    mode http
    default_backend haProxyBackend
    
backend haProxyBackend
    balance roundrobin
    option forwardfor
    server 4364-web-01 54.90.249.226:80 check
    server 4364-web-02 54.211.125.140:80 check
"
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy
sudo cp -a /etc/haproxy/haproxy.cfg{,.orig}
printf "%s" "$configurations" >> /etc/haproxy/haproxy.cfg
sudo service haproxy start
