#!/usr/bin/env bash
# script to install loadbalancer with provided configurations
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy=2.0.*
sudo apt-get -y install rsyslog
sudo sh -c "printf '%s' '$configurations' >> /etc/haproxy/haproxy.cfg"

configurations="
frontend haProxy
    bind *:80
    mode http
    default back_end haproxyBackend
    
backend haProxyBackend
    balance roundrobin
    mode http 
    option forwardfor
    server 4364-web-01 54.90.249.226:80 check
    server 4364-web-02 54.211.125.140:80 check
"
sudo sh -c "printf '%s' '$configurations' >> /etc/haproxy/haproxy.cfg"
sudo service haproxy start
